<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DefaultCountryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DefaultCountryRepository extends EntityRepository
{
}
