<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EncounterProcedureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EncounterProcedureRepository extends EntityRepository
{
    public function returnEncounterProcedures($encounter){
        return $this->createQueryBuilder('e')
            ->where("e.encounter = :encounter")
//            ->leftJoin('e.patient', 'patient')
//            ->leftJoin('e.provider', 'provider')
            ->setParameter('encounter', $encounter)
            ->getQuery()
            ->execute();
    }

}
