<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PaymentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentRepository extends EntityRepository
{
    public function returnPaymentsByPatient($patient){
        return $this->createQueryBuilder('p')
            ->where("p.patient = :patient")
            ->setParameter('patient', $patient)
            ->getQuery()
            ->execute();
    }

    public function returnPaymentsByDateAndOrMethod($start, $end, $paymentMethod = null){
        if($paymentMethod){
            return $this->createQueryBuilder('p')
                ->where("p.transactionDate >= :start")
                ->select("p.transactionDate", "p.paymentDate", "p.amount", "p.paymentMethod", "p.paymentNumber", "p.notes")
                ->andWhere("p.transactionDate <= :end")
                ->andWhere("p.paymentMethod = :method")
                ->setParameter('start', $start)
                ->setParameter('end', $end)
                ->setParameter('method', $paymentMethod)
                ->getQuery()
                ->execute();
        }else {
            return $this->createQueryBuilder('p')
                ->select("p.transactionDate", "p.paymentDate", "p.amount", "p.paymentMethod", "p.paymentNumber", "p.notes")
                ->where("p.transactionDate >= :start")
                ->andWhere("p.transactionDate <= :end")
                ->setParameter('start', $start)
                ->setParameter('end', $end)
                ->getQuery()
                ->execute();
        }
    }


}
