imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@ZfzmyrjlmjAuthenticationBundle/Resources/config/services.yml" }
    - { resource: "@ZfzmyrjlmjServeBundle/Resources/config/services.yml" }
    - { resource: "@ZfzmyrjlmjPatientBundle/Resources/config/services.yml" }
    - { resource: "@ChronoheedAuthBundle/Resources/config/services.yml" }
    - { resource: "@ChronoheedServeBundle/Resources/config/services.yml" }
    - { resource: "@ChronoheedPatientBundle/Resources/config/services.yml" }
    - { resource: "@ChronoheedCalendarBundle/Resources/config/services.yml" }
    - { resource: "@ChronoheedPaymentBundle/Resources/config/services.yml" }
    - { resource: "@ChronoheedUserBundle/Resources/config/services.yml" }
    - { resource: "@ChronoheedReportsBundle/Resources/config/services.yml" }
    - { resource: "@ChronoheedNotificationBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

#Sensio_framework_extra
sensio_framework_extra:
    view:   { annotations:  false }
    router: { annotations:   true }

#FOSRESTBUNDLE
fos_rest:
    format_listener:
        rules:
            - { path: ^/, priorities: [ 'json', 'xml', 'html' ], fallback_format: json, prefer_extension: false }
    view:
        view_response_listener: true

#fos_oauth_server
fos_oauth_server:
    db_driver:           orm
    client_class:           AppBundle\Entity\Client
    access_token_class:     AppBundle\Entity\AccessToken
    refresh_token_class:    AppBundle\Entity\RefreshToken
    auth_code_class:        AppBundle\Entity\AuthCode
    service:
        user_provider: fos_user.user_manager
        options:
            supported_scopes: user



#Fos User Bundle
fos_user:
    db_driver: orm
    firewall_name: api
    user_class: AppBundle\Entity\User

#Nelmio Configuration
nelmio_api_doc: ~

#nelmio cors bundle ///////////////  Jyhad REMEMBER TO LIMIT ACCESS TO THE API ***************************************
nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: []
        allow_headers: []
        allow_methods: []
        expose_headers: []
        max_age: 0
        hosts: []
        origin_regex: false
    paths:
        '^/api/':
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
            max_age: 3600
        '^/':
            origin_regex: true
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
            max_age: 3600

#Liip imagine
liip_imagine:
    filter_sets:
        patient_photo:
            quality: 75
            filters:
                thumbnail: { size: [400, 400], mode: outbound, allow_upscale: true }
        user_photo:
            quality: 75
            filters:
                thumbnail: { size: [400, 400], mode: outbound, allow_upscale: true }

#jms serializer for fos user entity
jms_serializer:
    metadata:
        directories:
            FOSUB:
                namespace_prefix: FOS\UserBundle
                path: %kernel.root_dir%/serializer/FOSUB

